### ISSUE TITLE
Table 'world._鍋囦汉_鍦ㄧ嚎鍋囦汉' doesn't exist

### ISSUE THREAD

**Issue by qqwqqwe** [normalzero/LegionPlayerBot#3]
Table 'world._？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？' doesn't exist

**Comment by qqwqqwe** [comment]
Add table manual operation.

**Comment by d3athbl0w** [comment]
Hello, would someone be so kind as to share the missing tables? Since they are in Chinese and even if I use a translator, I cannot decipher the tables to put them in English

**Comment by qqwqqwe** [comment]
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `_假人_在线假人`;
CREATE TABLE `_假人_在线假人` (
  `账号ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`账号ID`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;

**Comment by normalzero** [comment]
> Hello, would someone be so kind as to share the missing tables? Since they are in Chinese and even if I use a translator, I cannot decipher the tables to put them in English

You can import sql files with utf8 encoding
