### ISSUE TITLE
How to enter PlayerBots into world

### ISSUE THREAD

**Issue by slash-design** [normalzero/LegionPlayerBot#5]
How do I summon the Playerbots into the world?

In the source I find only the code for login or logout.
The accounts also log in.  This can be seen in the SQL database, but how do I summon the bots into the world?
I can't find this code in the source.

**Comment by d3athbl0w** [comment]
Have you managed to get the core up and running?

i have this error: https://github.com/normalzero/LegionPlayerBot/issues/3

**Comment by slash-design** [comment]
I have manually inserted the _假人_在线假人 table.
Name: 账号ID -- Type: int -- lenght: 10-- decimals: 0 -- auto Increment -- unsigned

**Comment by Aigon777** [comment]
i'm sorry, i want to add these bots to my private legion server 26972, how is it possible?
i've merged bot_auth.sql to auth and bot_world.sql to world.
But can't understand what to do then

**Comment by normalzero** [comment]
you can add bots with gm command within .cpp files you can search them

**Comment by normalzero** [comment]
> i'm sorry, i want to add these bots to my private legion server 26972, how is it possible? i've merged bot_auth.sql to auth and bot_world.sql to world. But can't understand what to do then

import sql files into database with utf8 encoding and then compile this project

**Comment by slash-design** [comment]
@normalzero soooo :)
the bots are now logging into the world. :-)

but....

the bots can cast spells, but the player cannot.
it always says "Must have a %s equipped"

do you have any idea what is wrong here?

**Comment by normalzero** [comment]
> @normalzero soooo :) the bots are now logging into the world. :-)
> 
> but....
> 
> the bots can cast spells, but the player cannot. it always says "Must have a %s equipped"
> 
> do you have any idea what is wrong here?

you can debug it
maybe just a CheckCast probelm
