### ISSUE TITLE
How to create a playerbot?

### ISSUE THREAD

**Issue by Simonlamb1979** [normalzero/LegionPlayerBot#6]
代码小白。编译后，进入游戏，如何添加playerbot的？
用了
.bot login ：没反应
.bot login 账号 ：也没反应。
.bot login 角色名 ：也没反应。

有谁能添加了机器人的，请求一下使用例子，谢谢了

**Comment by normalzero** [comment]
Ju

> 代码小白。编译后，进入游戏，如何添加playerbot的？ 用了 .bot login ：没反应 .bot login 账号 ：也没反应。 .bot login 角色名 ：也没反应。
> 
> 有谁能添加了机器人的，请求一下使用例子，谢谢了

Just see gm command within _Bot.cpp
